# This file contains values from Cookiecutter

default_context:
  project_name: "{{ cookiecutter.project_name }}"
  package_name: "{{ cookiecutter.package_name }}"
  git_platform: "{{ cookiecutter.git_platform }}"
  username: "{{ cookiecutter.username }}"
  git_repo_url: "{{ cookiecutter.git_repo_url }}"
  python_version: "{{ cookiecutter.python_version }}"
  line_length: "{{ cookiecutter.line_length }}"
